#!/usr/bin/env node
/**
 * art-palette — turn Grove's OKLCH tokens into something Figma can actually use.
 *
 * Grove's `tokens.css` contains no hex at all; every colour is `oklch()`. Figma cannot read that, so
 * the art would otherwise be drawn by eye. This converts the **installed** package's primitives to
 * sRGB hex and writes two artefacts:
 *
 *   src/assets/palette/palette.json   the machine-readable palette (also a diffable record of
 *                                     which Grove version the art was drawn against)
 *   src/assets/palette/swatches.svg   a labelled swatch sheet to open or import in Figma
 *
 * Both are generated. Re-run after any Grove bump and commit the diff — that diff is the record of
 * a palette change, and it tells you whether existing art needs recolouring.
 *
 *   node scripts/art-palette.mjs            write both artefacts
 *   node scripts/art-palette.mjs --check    verify the committed files match the installed tokens
 *   node scripts/art-palette.mjs --json     print the palette to stdout, write nothing
 *
 * Exit codes: 0 fine, 1 --check found drift, 2 bad usage or missing tokens.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { extractPalette, TOKENS_PATH } from "../src/lib/art/palette.mjs";

const OUT_DIR = "src/assets/palette";
const JSON_PATH = `${OUT_DIR}/palette.json`;
const SVG_PATH = `${OUT_DIR}/swatches.svg`;

const args = new Set(process.argv.slice(2));
const CHECK = args.has("--check");
const JSON_ONLY = args.has("--json");

for (const a of args) {
  if (!["--check", "--json"].includes(a)) {
    process.stderr.write(`Unknown flag: ${a}\n`);
    process.exit(2);
  }
}

if (!existsSync(TOKENS_PATH)) {
  process.stderr.write(
    `Grove tokens not found at ${TOKENS_PATH}.\nRun pnpm install first.\n`,
  );
  process.exit(2);
}

/** The installed Grove version, recorded so a palette diff is traceable to a bump. */
function groveVersion() {
  try {
    return JSON.parse(
      readFileSync("node_modules/@edgarjaymez/grove/package.json", "utf8"),
    ).version;
  } catch {
    return "unknown";
  }
}

const css = readFileSync(TOKENS_PATH, "utf8");
const { palette, conflicts } = extractPalette(css);

if (palette.length === 0) {
  process.stderr.write(
    `No primitives found in ${TOKENS_PATH}. Has the token format changed?\n`,
  );
  process.exit(2);
}

const families = [...new Set(palette.map((p) => p.family))].sort();

const manifest = {
  _note:
    "GENERATED by scripts/art-palette.mjs from the installed @edgarjaymez/grove tokens. Do not edit by hand. " +
    "These hex values are the sRGB baseline (the first :root declaration); tokens.css also carries wide-gamut " +
    "variants, which is what `variants` records. At inline time each hex becomes the fallback in " +
    "var(--token, #hex), so the live page still resolves the real token per theme and gamut.",
  groveVersion: groveVersion(),
  tokensPath: TOKENS_PATH,
  count: palette.length,
  families,
  colors: palette.map((p) => ({
    name: p.name,
    family: p.family,
    step: p.step,
    hex: p.hex,
    oklch: p.oklch,
    ...(p.clipped ? { outOfSrgbGamut: true } : {}),
    ...(p.variants.length ? { variants: p.variants } : {}),
  })),
};

if (JSON_ONLY) {
  process.stdout.write(JSON.stringify(manifest, null, 2) + "\n");
  process.exit(0);
}

// ---- swatch sheet -----------------------------------------------------------------------------

const SW = 140; // swatch width
const SH = 96; // swatch height
const GAP = 8;
const LABEL_H = 34;
const PAD = 40;
const HEADER = 64;

function escapeXml(s) {
  return String(s).replace(
    /[<>&"']/g,
    (c) =>
      ({
        "<": "&lt;",
        ">": "&gt;",
        "&": "&amp;",
        '"': "&quot;",
        "'": "&apos;",
      })[c],
  );
}

/** Pick black or white label text by relative luminance, so every label stays readable. */
function labelInk(hex) {
  const n = parseInt(hex.slice(1), 16);
  const [r, g, b] = [(n >> 16) & 255, (n >> 8) & 255, n & 255].map((v) => {
    const c = v / 255;
    return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  });
  const lum = 0.2126 * r + 0.7152 * g + 0.0722 * b;
  return lum > 0.45 ? "#000000" : "#ffffff";
}

function buildSwatchSheet() {
  const rows = families.map((family) =>
    palette.filter((p) => p.family === family),
  );
  const cols = Math.max(...rows.map((r) => r.length));
  const width = PAD * 2 + cols * SW + (cols - 1) * GAP;
  const height = HEADER + PAD * 2 + rows.length * (SH + LABEL_H + GAP * 3);

  const parts = [];
  parts.push(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">`,
  );
  parts.push(`<rect width="${width}" height="${height}" fill="#ffffff"/>`);
  parts.push(
    `<text x="${PAD}" y="40" font-family="sans-serif" font-size="24" font-weight="700" fill="#111111">` +
      `Grove primitives — the only legal palette for journey art</text>`,
  );
  parts.push(
    `<text x="${PAD}" y="58" font-family="sans-serif" font-size="13" fill="#555555">` +
      `@edgarjaymez/grove ${escapeXml(manifest.groveVersion)} · ${palette.length} colours · ` +
      `generated by scripts/art-palette.mjs · ✳ = shifts on a wide-gamut display</text>`,
  );

  let y = HEADER + PAD;
  for (const row of rows) {
    parts.push(
      `<text x="${PAD}" y="${y - 8}" font-family="sans-serif" font-size="15" font-weight="600" fill="#111111">` +
        `${escapeXml(row[0].family)}</text>`,
    );
    row.forEach((c, i) => {
      const x = PAD + i * (SW + GAP);
      const ink = labelInk(c.hex);
      parts.push(
        `<rect x="${x}" y="${y}" width="${SW}" height="${SH}" fill="${c.hex}"/>`,
      );
      parts.push(
        `<text x="${x + 10}" y="${y + SH - 12}" font-family="monospace" font-size="13" fill="${ink}">` +
          `${escapeXml(c.hex)}${c.variants.length ? " ✳" : ""}</text>`,
      );
      parts.push(
        `<text x="${x}" y="${y + SH + 18}" font-family="monospace" font-size="12" fill="#111111">` +
          `--${escapeXml(c.name)}</text>`,
      );
      parts.push(
        `<text x="${x}" y="${y + SH + 32}" font-family="sans-serif" font-size="10" fill="#666666">` +
          `${escapeXml(c.oklch)}</text>`,
      );
    });
    y += SH + LABEL_H + GAP * 3;
  }

  parts.push("</svg>");
  return parts.join("\n") + "\n";
}

const jsonOut = JSON.stringify(manifest, null, 2) + "\n";
const svgOut = buildSwatchSheet();

if (CHECK) {
  const problems = [];
  for (const [path, want] of [
    [JSON_PATH, jsonOut],
    [SVG_PATH, svgOut],
  ]) {
    if (!existsSync(path)) problems.push(`${path} is missing.`);
    else if (readFileSync(path, "utf8") !== want)
      problems.push(`${path} is stale.`);
  }
  if (problems.length) {
    for (const p of problems) process.stderr.write(`${p}\n`);
    process.stderr.write(
      `\nGrove is at ${manifest.groveVersion}. Run: node scripts/art-palette.mjs\n`,
    );
    process.exit(1);
  }
  process.stdout.write(
    `palette up to date — ${palette.length} colours from grove ${manifest.groveVersion}\n`,
  );
  process.exit(0);
}

mkdirSync(dirname(JSON_PATH), { recursive: true });
writeFileSync(JSON_PATH, jsonOut);
writeFileSync(SVG_PATH, svgOut);

process.stdout.write(
  `grove ${manifest.groveVersion} — ${palette.length} primitives across ${families.length} families\n`,
);
process.stdout.write(`  ${JSON_PATH}\n  ${SVG_PATH}\n`);
if (conflicts.length) {
  process.stdout.write(
    `\n${conflicts.length} token(s) also ship wide-gamut variants; the sRGB baseline is used and marked ✳:\n`,
  );
  for (const c of conflicts)
    process.stdout.write(`  --${c.name}: ${c.values.join(" / ")}\n`);
}
const clipped = palette.filter((p) => p.clipped);
if (clipped.length) {
  process.stdout.write(
    `\n${clipped.length} colour(s) fall outside sRGB and were clipped:\n`,
  );
  for (const c of clipped) process.stdout.write(`  --${c.name} → ${c.hex}\n`);
}
